language: cpp
dist: focal
sudo: required
os: linux

compiler: g++

addons:
  apt:
    packages:
      - gcc
      - g++
      - cmake

      - libgtest-dev
      - libzmq5 
      - libzmq3-dev

      - python3.6
      - python3-pip
      - golang

      - libgstreamer1.0-0
      - libgstreamer1.0-dev 
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good 
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-libav 
      - gstreamer1.0-tools 
      - gstreamer1.0-x 
      - gstreamer1.0-alsa 
      - gstreamer1.0-pulseaudio

install:
  - go get github.com/pebbe/zmq4
  - pip3 install setuptools
  - pip3 install pyzmq termcolor

script:

  # GTEST SETTING
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - cd /home/travis/build/szymonjanas/PiRadioApp

  # COMPILE AND RUN
  - cd scripts
  - ./build.sh
  - cd ..
  - ./build/PiRadioApp-engine-utests

  - python3 tests/

  - cd scripts/
  - sh deploy-tar.sh
  - cd ..
  - cd deploy/tar/piradio/
  - sudo sh INSTALL.sh
  - cd /opt/PiRadioApp
  - sudo sh uninstall.sh
  - cd /home/travis/build/szymonjanas/PiRadioApp/scripts
  - sh clean.sh
  
  - cd ..
  - python3 tests/ --test-when-running

