language: cpp
dist: trusty
sudo: required
os: linux

compiler:
  - gcc
launguage: python
python:
  - "3.6" 

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6

install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio
  - sudo apt install libzmq3-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./PiRadioApp-engine-tests
  - cd ..
  - python server-api-tests/
