language: cpp
dist: bionic
sudo: required
os: linux

compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - gcc-6
      - g++-6
      - cmake

      - libgtest-dev
      - libzmq5 
      - libzmq3-dev

      - python3.6
      - python3-pip
      - golang

      - libgstreamer1.0-0
      - libgstreamer1.0-dev 
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good 
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-libav 
      - gstreamer1.0-tools 
      - gstreamer1.0-x 
      - gstreamer1.0-alsa 
      - gstreamer1.0-pulseaudio

install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - go get github.com/pebbe/zmq4
  - pip3 install setuptools
  - pip3 install pyzmq flask termcolor

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./PiRadioApp-engine-utests

  - cd ..
  - python3 tests/engine-ipc-test --engine
